"use client";
import {useEffect,useState} from 'react';
type Rate={input:number;output:number};
type Report={budget:{dailyYen:number;monthlyYen:number;yenPerUsd:number;rates:Record<string,Rate>};todayYen:number;monthYen:number;since:number|null;models:{model:string;calls:number;inputTokens:number|null;outputTokens:number|null;yen:number;estimated:number}[];recent:{created_at:number;model:string;purpose:string;status:string;cost_yen:number}[]};
const purposeLabel:Record<string,string>={summary_classification:'要約・分類',classification:'分類',detail:'詳細要約・翻訳',other:'その他'};
const statusLabel=(s:string)=>({reserved:'処理中',success:'完了',failed:'失敗',interrupted:'中断'}[s.replace('_estimated','')]??s)+(s.endsWith('_estimated')?'（使用量不明）':'');
const yen=(n:number)=>n.toLocaleString('ja-JP',{minimumFractionDigits:2,maximumFractionDigits:2});
export function AIUsagePanel({models}:{models:string[]}){
 const [report,setReport]=useState<Report|null>(null),[budget,setBudget]=useState<Report['budget']|null>(null),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/ai/usage');if(!r.ok)throw Error('利用量を取得できませんでした');const d=await r.json();if(active){setReport(d);setBudget(b=>b??d.budget);}}catch(e){if(active)setMessage((e as Error).message);}};load();const t=setInterval(load,15000);return()=>{active=false;clearInterval(t)};},[]);
 if(!report||!budget)return <p className="text-sm" role="status">{message||'AI利用量を読み込み中…'}</p>;
 const inputStyle={background:'var(--bg)',color:'var(--fg)',border:'1px solid var(--card-border)'};
 const configured=[...new Set(models)];
 return <section className="settings-card settings-usage space-y-4" style={{borderColor:'var(--card-border)',background:'var(--card)'}}>
 <h2 className="text-sm font-semibold">AI費用・予算</h2>
 <div className="settings-metrics">{[{label:'今日の概算',amount:report.todayYen,limit:report.budget.dailyYen},{label:'今月の概算',amount:report.monthYen,limit:report.budget.monthlyYen}].map(item=><div className="settings-metric" key={item.label}><p>{item.label}</p><strong>¥{yen(item.amount)}</strong><div className="settings-meter" role="meter" aria-label={`${item.label}の予算使用率`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={item.limit>0?Math.min(100,item.amount/item.limit*100):0}><span style={{width:`${item.limit>0?Math.min(100,item.amount/item.limit*100):0}%`}}/></div><small>{item.limit===0?'新しいAI呼び出しは停止中':`上限 ¥${item.limit.toLocaleString()} · 残り ¥${yen(Math.max(0,item.limit-item.amount))}`}</small></div>)}</div>
 <details className="settings-disclosure"><summary>概算費用の計算について</summary>
 <p className="text-xs leading-relaxed" style={{color:'var(--muted)'}}>記録開始：{report.since?new Date(report.since).toLocaleString('ja-JP'):'まだ呼び出しがありません'}。このYomuから呼び出した分を記録します。同じAPIキーを使う別の環境・過去の利用分・税・無料枠・割引は含みません。APIの使用量と登録単価による概算です。失敗・中断で使用量が不明な呼び出しは、予約額を残して予算に算入します。</p>
 </details>
 <h3 className="settings-subheading">使いすぎを防ぐ予算</h3>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{(['dailyYen','monthlyYen','yenPerUsd'] as const).map((key,i)=><label key={key} className="text-xs">{['日額上限（円）','月額上限（円）','換算：1ドルあたり円'][i]}<input aria-label={['日額上限（円）','月額上限（円）','換算：1ドルあたり円'][i]} type="number" min={key==='yenPerUsd'?1:0} value={budget[key]} onChange={e=>setBudget({...budget,[key]:Number(e.target.value)})} className="mt-1 w-full rounded p-2" style={inputStyle}/></label>)}</div>
 <p className="text-xs" style={{color:'var(--muted)'}}>呼び出し前に入力と最大出力量の概算を予約します。上限に収まらない処理は待機し、0円にすると新しいAI呼び出しを停止します。請求元の厳密な課金上限ではありません。</p>
 <details className="settings-disclosure"><summary className="cursor-pointer text-xs">モデル単価（100万トークンあたりUSD）</summary><p className="my-2 text-xs" style={{color:'var(--muted)'}}>Gemini 3 Flash Preview・2.5 Flash・2.5 Flash-Liteは公式の通常テキスト単価を初期登録しています（2026-09-10確認）。他モデルは公式単価の登録が必要です。変更は以後の呼び出しに適用されます。</p>{configured.map(model=><div className="my-2 flex flex-wrap items-end gap-2" key={model}><span className="w-full text-xs">{model}</span>{(['input','output'] as const).map(key=><label key={key} className="text-xs">{key==='input'?'入力単価':'出力単価'}<input aria-label={`${model} ${key}`} className="ml-2 w-24 rounded p-1" style={inputStyle} type="number" min="0.001" step="0.01" value={budget.rates[model]?.[key]??''} onChange={e=>setBudget({...budget,rates:{...budget.rates,[model]:{...(budget.rates[model]??{input:0,output:0}),[key]:Number(e.target.value)}}})}/></label>)}</div>)}<a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noopener noreferrer" className="text-xs underline">Gemini公式料金 ↗</a></details>
 <button disabled={saving} onClick={async()=>{setSaving(true);try{const r=await fetch('/api/ai/usage',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(budget)});const d=await r.json();if(!r.ok)throw Error(d.error||'保存に失敗しました');setReport(d);setBudget(d.budget);setMessage('予算を保存しました');}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}} className="rounded px-3 py-2 text-xs" style={{background:'var(--accent)',color:'var(--accent-fg)'}}>{saving?'保存中…':'予算・単価を保存'}</button><span role="status" className="ml-3 text-xs">{message}</span>
 {report.models.length>0&&<div className="settings-model-usage"><h3 className="settings-subheading">モデル別の利用額 <small>今月の記録分</small></h3>{report.models.map(m=><div className="settings-model-row" key={m.model}><div><strong>{m.model}</strong><p>{m.calls.toLocaleString()}回 · 入力 {(m.inputTokens??0).toLocaleString()} / 出力 {(m.outputTokens??0).toLocaleString()} トークン</p>{m.estimated>0&&<p>使用量不明 {m.estimated}件</p>}</div><span>¥{yen(m.yen)}</span></div>)}</div>}
 <details className="settings-disclosure"><summary className="cursor-pointer text-xs">最近の呼び出し</summary>{report.recent.map((r,i)=><div key={i} className="mt-2 text-xs" style={{color:'var(--muted)'}}>{new Date(r.created_at).toLocaleTimeString('ja-JP')} · {r.model} · {purposeLabel[r.purpose]??r.purpose} · {statusLabel(r.status)} · ¥{yen(r.cost_yen)}</div>)}</details>
 </section>;
}
